#!/usr/bin/env bash
# =============================================================================
#  attack-scan.sh -- simulate an internal network scan (reconnaissance)
# -----------------------------------------------------------------------------
#  Opt-in demo attack. Runs an nmap TCP-connect scan of the PROD /28 from a
#  workstation, fanning out over SSH/HTTP/HTTPS/PostgreSQL/app ports. obserae
#  should surface a single source touching many hosts/ports (scan pattern).
#
#  Usage:  ./scripts/attack-scan.sh [count] [ws-service]
#            count       how many scan bursts to run   (default 5)
#            ws-service  workstation to run it from     (default ws2, the "ops" role)
#
#  Nothing is generated by default; run this only when you want to observe the
#  scan in obserae. See it in obserae with, e.g.:
#    FROM sessions | WHERE src_addr == "workstations" AND dst_addr == "PROD"
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root (where docker-compose.yml lives)

COUNT="${1:-5}"
WS="${2:-ws2}"
TARGET="10.0.20.0/28"      # PROD segment
PORTS="22,80,443,5432,8000"

# Docker must be reachable. In this lab that usually means running with sudo;
# fail loudly here instead of hanging silently later.
if ! docker version >/dev/null 2>&1; then
  echo "ERROR: cannot reach the Docker daemon. Run this script with the same" >&2
  echo "       privileges you use for docker, e.g.  sudo $0" >&2
  exit 1
fi

echo "==> Scanning ${TARGET} (ports ${PORTS}) from ${WS}, ${COUNT} burst(s)..."
for i in $(seq 1 "${COUNT}"); do
  echo "    burst ${i}/${COUNT}"
  docker compose exec -T "${WS}" \
    nmap -sT -Pn --max-retries 1 --host-timeout 8s -p "${PORTS}" "${TARGET}" \
    >/dev/null 2>&1 || true
  sleep 2
done

cat <<EOF

Done. A workstation just port-scanned the PROD /28. Look at it in obserae:
  - Cartography / Detection: ${WS} fanning out to many PROD hosts/ports.
  - NFQL:
      FROM sessions | WHERE src_addr == "workstations" AND dst_addr == "PROD"
EOF
